name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        run: npx playwright test --reporter=html

      - name: Check if report folder exists
        run: |
          if [ ! -d "playwright-report" ]; then
            echo "❌ playwright-report not found!"
            exit 1
          fi

      - name: Compress Playwright Report
        run: zip -r playwright-report.zip playwright-report

      - name: Send Report via Email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Playwright Test Report 📋
          to: ${{ secrets.MAIL_RECEIVER }}
          from: Playwright CI <${{ secrets.MAIL_USERNAME }}>
          body: |
            Hello,

            The Playwright test suite has completed. Please find the HTML test report attached.

            ✅ Branch: ${{ github.ref }}
            🔁 Commit: ${{ github.sha }}

            Regards,  
            GitHub Actions
          attachments: playwright-report.zip
